---
- name: Deploy GitLab + Forgejo git services stack
  hosts: git_services
  become: true
  vars:
    git_services_gitlab_http_port: 8929
    git_services_gitlab_ssh_port: 2224
    git_services_forgejo_http_port: 3001
  roles:
    - git_services
